# Generated by Django 2.2 on 2020-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='first',
            options={'verbose_name_plural': 'Firsts'},
        ),
        migrations.AddField(
            model_name='first',
            name='city',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='first',
            name='image1',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
        migrations.AddField(
            model_name='first',
            name='image2',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
        migrations.AddField(
            model_name='first',
            name='image3',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='first',
            name='event',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
