# Generated by Django 3.0.6 on 2020-05-17 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_first_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='first',
            name='video_url',
            field=models.URLField(default=1),
        ),
        migrations.AlterField(
            model_name='first',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 18, 5, 21, 680477), verbose_name='date_published'),
        ),
    ]
