# Generated by Django 3.0.6 on 2020-05-17 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20200517_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='city',
            field=models.CharField(default='Chennai/Solapur', max_length=200),
        ),
        migrations.AlterField(
            model_name='first',
            name='event',
            field=models.CharField(default='Type the event here', max_length=200),
        ),
        migrations.AlterField(
            model_name='first',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 18, 18, 2, 473932), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='first',
            name='video_url',
            field=models.URLField(default='.com'),
        ),
    ]
